/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DAO.ItemDAO;
import Model.Item;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Pedro
 */
public class frmCadastroProduto extends javax.swing.JFrame {
    
    private JTextField txtIdProduto;
    private JTextField txtNome;
    private JTextField txtUnidade;
    private JTextField txtPreco;
    private JTextField txtDescricao;
    private JButton btnCadastrar;
    
    private ProdutoController produtoController;
    private DefaultListModel<String> listaProdutosModel;
    private JList<String> listaProdutos;

    /**
     * Creates new form frmCadastroProduto
     */
    public frmCadastroProduto() {
        //Configuração básica da janela
        setTitle("Cadastro de Produto");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Inicialização do controlador e do modelo da lista
        produtoController = new ProdutoController();
        listaProdutosModel = new DefaultListModel<>();

        // Criando os componentes
        JLabel lblIdProduto = new JLabel("ID do Produto:");
        JLabel lblNome = new JLabel("Nome:");
        JLabel lblUnidade = new JLabel("Unidade:");
        JLabel lblPreco = new JLabel("Preço:");
        JLabel lblDescricao = new JLabel("Descrição:");

        txtIdProduto = new JTextField(10);
        txtNome = new JTextField(20);
        txtUnidade = new JTextField(10);
        txtPreco = new JTextField(10);
        txtDescricao = new JTextField(20);

        btnCadastrar = new JButton("Cadastrar");

        // Adicionando os ouvintes de eventos aos botões
        btnCadastrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                float preco = Float.parseFloat(txtPreco.getText());
                Item produto = new Item(0, txtDescricao.getText(), preco, txtUnidade.getText());
                ItemDAO itemBanco = new ItemDAO();
                itemBanco.InserirItem(produto);
            }
        });


        // Configurando a lista de produtos
        listaProdutos = new JList<>(listaProdutosModel);
        JScrollPane scrollPane = new JScrollPane(listaProdutos);

        // Configurando o layout
        setLayout(new BorderLayout());

        JPanel formularioPanel = new JPanel(new GridLayout(6, 2, 5, 5));
        formularioPanel.add(lblIdProduto);
        formularioPanel.add(txtIdProduto);
        formularioPanel.add(lblNome);
        formularioPanel.add(txtNome);
        formularioPanel.add(lblUnidade);
        formularioPanel.add(txtUnidade);
        formularioPanel.add(lblPreco);
        formularioPanel.add(txtPreco);
        formularioPanel.add(lblDescricao);
        formularioPanel.add(txtDescricao);
        formularioPanel.add(btnCadastrar);

        add(formularioPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);

        // Exibindo a janela
        setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
class Produto {
    private int idProduto;
    private String nome;
    private String unidade;
    private double preco;
    private String descricao;

    public Produto(int idProduto, String nome, String unidade, double preco, String descricao) {
        this.idProduto = idProduto;
        this.nome = nome;
        this.unidade = unidade;
        this.preco = preco;
        this.descricao = descricao;
    }

    public int getIdProduto() {
        return idProduto;
    }

    public String getNome() {
        return nome;
    }

    public String getUnidade() {
        return unidade;
    }

    public double getPreco() {
        return preco;
    }

    public String getDescricao() {
        return descricao;
    }
}

class ProdutoController {
    private java.util.List<Produto> produtos;

    public ProdutoController() {
        produtos = new java.util.ArrayList<>();
    }

    public void adicionarProduto(Produto produto) {
        produtos.add(produto);
    }

    public List<Produto> getProdutos() {
        return produtos;
    }
}